baseurl: ""
# url: 'http://0.0.0.0:4000/'
url: 'http://blazecup.no/'
destination: docs
markdown: kramdown
collections:
    runners:
sass:
    sass_dir: _style
    style: compressed
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            published: 'true'

prose:
    rooturl: _runners
    media: media
    siteurl: 'http://blazecup.no/'
    relativeLinks: 'http://blazecup.no/links.jsonp'
    metadata:
        _runners:
            - {name: title, field: {element: text, value: ""}}
            - {name: published, field: {element: hidden, value: 'true'}}
            - {name: name, field: {element: text, label: 'Name', placeholder: 'Anders Martinsen', value: ""}}
            - {name: insta_user, field: {element: text, label: 'Insta username', placeholder: 'hanserino', value: ""}}
            - {name: strava_id, field: {element: text, label: Strava ID, placeholder: '10448277', value: ""}}
            - {name: stirsdag_time, field: {element: text, label: Stirsdag time, placeholder: '57:45:00', value: ""}}
            - {name: lilo_trail_time, field: {element: text, label: Lilo Trail time, placeholder: '2:15:43', value: ""}}
            - {name: lillomarka_rundt_time, field: {element: text, label: Lillomarka Rundt time, placeholder: '5:35:21', value: ""}}
